<?php
/* PARA RESERVAR DEBE SER CON 5 DIAS DE ANTELACION, PUEDE RESERVAR 10 EQUIPOS MÁX. PUEDE CANCELAR LA RESERVA

FORMULARIO PARA TERMINAR DE LLENAR LOS DATOS. 
NOMBRE , CANTIDAD DE DIAS DE RESERVA, 

SI CANCELA LA RESERVA, SE LE HACE UNA MULTA DEL 10% DEL TOTAL DE LA RESERVA 
*/
if(isset($_GET)){
    
}


?>